#
# ForestMOTD v1.0.1
#
# | If you find bug or you have an idea for an adjustment, please contact us on
#   https://discord.com/invite/2PpdrfxhD4
#
# | %online% - Return number of players on server
# | %defaultMax% - Default server max server player size
# | %version% - Server version
# | %configPlayersMax% - Config player max number
#
# | Permission = forestMOTD.admin
#

#
# MOTD
#
# | Use ":n:" to do second line
#   "maxPlayers: -1" - This will set default server number
#
motd:
  maxPlayers: 69
# | 64x64 size icon
  iconName: "server-icon.png"
  text: "{#30FF5A>}&lForest{#7DFFC2<}&f&lMOTD:n:&rBest server in the Universe!"
#
# | If you want to use hover box on spigot, download ProtocolLib! (5.0.0+)
#
  hoverBox:
  - "&c❤  &a&lForest&7&lTech &c❤"
  - " "
  - " &aPlugins with &c❤"
  - " "

#
# | Messages
#
message:
  noPerm: "{#malachite>}&lForest{#bluestone<}&f&lMOTD &7You don't have sufficient permissions..."
  reload: "{#malachite>}&lForest{#bluestone<}&f&lMOTD &7Config & Data reloaded..."
